use std::time::Duration;

use futures::stream;
use tokio_stream::StreamExt;

use super::types::*;

pub struct StubProvider;

impl StubProvider {
    pub fn new() -> Self {
        Self
    }

    pub async fn generate(&self, _request: &LlmRequest) -> Result<LlmResponse, LlmError> {
        let scenario = pick_stub(_request);
        Ok(LlmResponse {
            content: scenario.to_string(),
            prompt_tokens: 150,
            completion_tokens: 400,
            model: "stub-v1".into(),
        })
    }

    pub fn generate_stream(&self, request: &LlmRequest) -> StreamResult {
        let text = pick_stub(request).to_string();
        let words: Vec<String> = text.split_whitespace().map(|w| format!("{w} ")).collect();
        Box::pin(
            stream::iter(words)
                .then(|word| async move {
                    tokio::time::sleep(Duration::from_millis(50)).await;
                    Ok(word)
                })
        )
    }
}

fn pick_stub(req: &LlmRequest) -> &'static str {
    // ponytail: rotate through canned scenarios based on prompt length hash
    let idx = req.user_prompt.len() % STUBS.len();
    STUBS[idx]
}

const STUBS: &[&str] = &[
    r#"{"title":"ARCTIC FLASHPOINT","description":"SITREP: Russian Northern Fleet has deployed three Borei-class SSBNs to patrol positions under the Arctic ice shelf. NATO SOSUS arrays detected abnormal submarine activity near the GIUK gap. Norwegian coastal radar reports unidentified surface contacts heading southwest.\n\nINTELLIGENCE ASSESSMENT: This deployment exceeds normal rotation patterns. Coincides with Russian suspension of the New START inspection regime. DEFCON advisory recommends heightened ASW readiness across Atlantic Command.","threat_level":"High","affected_regions":["Arctic Ocean","Norwegian Sea","GIUK Gap","Barents Sea"],"player_options":[{"id":1,"label":"Deploy P-8 Poseidon ASW","description":"Send maritime patrol aircraft to track submarine movements — reveals positions but escalates tensions"},{"id":2,"label":"Activate NATO Article 4","description":"Convene emergency consultations — diplomatic but slow"},{"id":3,"label":"Open diplomatic back-channel","description":"Contact Russian MoD directly — risks appearing weak but may defuse"},{"id":4,"label":"Increase DEFCON readiness","description":"Raise alert level — sends strong signal but narrows de-escalation window"}],"comms":[{"origin":"Russia","native_text":"Министерство обороны сообщает: плановые учения Северного флота проходят в штатном режиме. Иностранным судам рекомендовано покинуть зону учений.","english_translation":"Ministry of Defense reports: planned Northern Fleet exercises proceeding normally. Foreign vessels advised to leave exercise zone.","priority":"Priority"},{"origin":"NATO","native_text":"ALLIED MARITIME COMMAND: SIGINT confirms three SSBN departures from Gadzhiyevo. Tracking assets repositioning.","english_translation":"ALLIED MARITIME COMMAND: SIGINT confirms three SSBN departures from Gadzhiyevo. Tracking assets repositioning.","priority":"Immediate"}]}"#,

    r#"{"title":"DRAGON'S REACH","description":"SITREP: PLA Navy carrier group Shandong has entered disputed waters near the Second Island Chain. Satellite imagery confirms J-35 stealth fighters conducting launch operations. Simultaneously, PLA Rocket Force has activated mobile TEL launchers in Fujian province — DF-21D anti-ship ballistic missiles now in pre-launch configuration.\n\nINTELLIGENCE ASSESSMENT: Activity correlates with diplomatic breakdown at the ASEAN Regional Forum. Taiwan has raised its military readiness to Level 2. Japan has scrambled F-35s from Kadena.","threat_level":"Critical","affected_regions":["Taiwan Strait","South China Sea","Fujian Province","Okinawa"],"player_options":[{"id":1,"label":"Reposition 7th Fleet","description":"Move carrier group to Philippine Sea — show of force, high escalation risk"},{"id":2,"label":"UN Security Council session","description":"Push for emergency session — China will likely veto but creates diplomatic record"},{"id":3,"label":"Back-channel Beijing","description":"Engage PRC foreign ministry through unofficial channels — preserves deniability"},{"id":4,"label":"Share intelligence with allies","description":"Brief Japan, Australia, Philippines on PLA movements — builds coalition but risks leak"}],"comms":[{"origin":"China","native_text":"中央军委通告：中国人民解放军海军在本国领海范围内进行例行训练，任何外部势力不得干涉中国内政。","english_translation":"Central Military Commission announces: PLA Navy conducting routine training within sovereign waters. External forces must not interfere in China's internal affairs.","priority":"Flash"},{"origin":"USA","native_text":"PACOM FLASH: Carrier Strike Group Five repositioning per OPLAN contingency. All units condition REDCON-2.","english_translation":"PACOM FLASH: Carrier Strike Group Five repositioning per OPLAN contingency. All units condition REDCON-2.","priority":"Flash"}]}"#,

    r#"{"title":"GHOST CIRCUIT","description":"SITREP: Coordinated cyber intrusion detected across NATO member power grids. Malware signature matches SANDWORM APT group. Estonia, Poland, and Germany reporting rolling blackouts affecting military installations. USCYBERCOM has traced command-and-control servers to infrastructure in Belarus.\n\nINTELLIGENCE ASSESSMENT: Attack pattern suggests pre-positioning for larger operation. Similar TTPs preceded the 2015 Ukraine grid attack. No kinetic military movements detected — this may be a standalone operation or a precursor.","threat_level":"High","affected_regions":["Estonia","Poland","Germany","Belarus"],"player_options":[{"id":1,"label":"Counter-cyber operation","description":"Authorize USCYBERCOM to neutralize C2 servers — effective but crosses cyber-warfare threshold"},{"id":2,"label":"NATO Article 5 debate","description":"Invoke collective defense clause for cyber attack — unprecedented, sets major precedent"},{"id":3,"label":"Diplomatic demarche","description":"Formal protest to Belarus and Russia — conventional response, limited deterrent effect"},{"id":4,"label":"Isolate affected networks","description":"Defensive posture only — contains damage but adversary retains initiative"}],"comms":[{"origin":"Russia","native_text":"Кремль передаёт: Российская Федерация категорически отрицает причастность к кибератакам на инфраструктуру стран НАТО.","english_translation":"Kremlin transmits: Russian Federation categorically denies involvement in cyber attacks on NATO infrastructure.","priority":"Immediate"},{"origin":"NATO","native_text":"SHAPE CYBER OPS: Threat level SUBSTANTIAL. All member states activate national cyber defense protocols immediately.","english_translation":"SHAPE CYBER OPS: Threat level SUBSTANTIAL. All member states activate national cyber defense protocols immediately.","priority":"Immediate"}]}"#,

    r#"{"title":"BROKEN ARROW","description":"SITREP: NORAD early warning satellites detected a thermal bloom over the Kapustin Yar test range consistent with an ICBM launch. Trajectory analysis indicates the missile is on a sub-orbital test trajectory terminating in the Kamchatka impact zone. However, no prior notification was provided through established deconfliction channels.\n\nINTELLIGENCE ASSESSMENT: Russia has conducted unannounced missile tests before, but never during a period of elevated tensions. The lack of prior notification violates the Hague Code of Conduct. STRATCOM is tracking the object and has not classified it as a threat — yet.","threat_level":"Critical","affected_regions":["Kapustin Yar","Kamchatka","Pacific Ocean","CONUS"],"player_options":[{"id":1,"label":"Contact Moscow on hotline","description":"Direct leader-to-leader communication — fastest de-escalation path"},{"id":2,"label":"Raise DEFCON to 3","description":"Prudent military response — signals seriousness without overreaction"},{"id":3,"label":"Scramble B-2 bombers","description":"Visible deterrent signal — extremely escalatory"},{"id":4,"label":"Monitor and assess","description":"Wait for more data — risks appearing passive but avoids premature escalation"}],"comms":[{"origin":"Russia","native_text":"Министерство обороны сообщает: запуск баллистической ракеты произведён в рамках плановых испытаний. Угрозы для иностранных государств нет.","english_translation":"Ministry of Defense reports: ballistic missile launch conducted as part of planned tests. No threat to foreign states.","priority":"Flash"},{"origin":"USA","native_text":"STRATCOM OPREP-3: PINNACLE event. Unannounced Russian ICBM test detected. Tracking nominal. No threat assessment at this time.","english_translation":"STRATCOM OPREP-3: PINNACLE event. Unannounced Russian ICBM test detected. Tracking nominal. No threat assessment at this time.","priority":"Flash"}]}"#,

    r#"{"title":"IRON CURTAIN 2.0","description":"SITREP: Multiple NATO member states report GPS spoofing affecting military and civilian aircraft across the Baltic region. Simultaneously, Russia has announced closure of international airspace over Kaliningrad for 'military exercises' — effectively creating an air corridor denial zone between NATO's eastern flank.\n\nINTELLIGENCE ASSESSMENT: GPS disruption originates from electronic warfare systems deployed in Kaliningrad. Pattern matches Krasukha-4 jamming capability. Combined with airspace closure, this creates a de facto A2/AD bubble threatening NATO's ability to reinforce Baltic states.","threat_level":"Medium","affected_regions":["Baltic Sea","Kaliningrad","Lithuania","Latvia","Estonia"],"player_options":[{"id":1,"label":"Deploy NATO EW assets","description":"Counter-jam Russian systems — technical escalation but restores capability"},{"id":2,"label":"Reroute air traffic","description":"Avoid contested airspace — concedes tactical advantage but avoids incident"},{"id":3,"label":"Formal ICAO complaint","description":"International aviation body protest — slow but legally grounded"},{"id":4,"label":"Enhanced Forward Presence","description":"Surge troops to Baltic states — strong signal but logistically demanding"}],"comms":[{"origin":"Russia","native_text":"Кремль передаёт: временное закрытие воздушного пространства над Калининградской областью — стандартная мера обеспечения безопасности учений.","english_translation":"Kremlin transmits: temporary airspace closure over Kaliningrad Oblast is a standard exercise safety measure.","priority":"Priority"},{"origin":"NATO","native_text":"ALLIED AIR COMMAND: GPS degradation confirmed across Baltics. All aircraft switch to INS backup navigation. Avoid Kaliningrad FIR.","english_translation":"ALLIED AIR COMMAND: GPS degradation confirmed across Baltics. All aircraft switch to INS backup navigation. Avoid Kaliningrad FIR.","priority":"Immediate"}]}"#,

    r#"{"title":"SILK ROAD SEVERANCE","description":"SITREP: Intelligence reports indicate coordinated economic warfare targeting NATO supply chains. Chinese state-linked firms have simultaneously restricted rare earth mineral exports, while Russian energy company Gazprom announced 'maintenance shutdowns' on three major European gas pipelines. Global semiconductor production faces 60-day disruption.\n\nINTELLIGENCE ASSESSMENT: Coordinated timing suggests pre-planned economic pressure campaign. European energy reserves at 40% capacity. Defense industrial base reports critical shortages in guidance system components.","threat_level":"Medium","affected_regions":["European Union","Pacific Rim","Global Supply Chains"],"player_options":[{"id":1,"label":"Invoke emergency stockpiles","description":"Release strategic reserves — buys 90 days but depletes buffer"},{"id":2,"label":"Economic counter-sanctions","description":"Target Russian and Chinese financial systems — mutual economic damage"},{"id":3,"label":"Emergency allied summit","description":"Coordinate response with G7 — unified front but delays action"},{"id":4,"label":"Accelerate domestic production","description":"Fast-track reshoring initiatives — long-term fix, no short-term relief"}],"comms":[{"origin":"China","native_text":"北京指挥部报告：稀土出口管制属于正常贸易政策调整，不针对任何特定国家。","english_translation":"Beijing Command reports: rare earth export controls are normal trade policy adjustments, not targeting any specific country.","priority":"Priority"},{"origin":"NATO","native_text":"ALLIED COMMAND TRANSFORMATION: Supply chain disruption assessment — CRITICAL. Recommend immediate activation of resilience protocols.","english_translation":"ALLIED COMMAND TRANSFORMATION: Supply chain disruption assessment — CRITICAL. Recommend immediate activation of resilience protocols.","priority":"Immediate"}]}"#,
];
